### ISSUE TITLE
[Error: spawn EACCES]

### ISSUE THREAD

**Issue by jalynxing** [choerodon/choerodon-front-iam#2]
I get an error after executing the `npm start` command on  Mac system: [Error: spawn EACCES], the detailed log is:
```
0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/bin/node', '/usr/local/bin/npm', 'start' ]
2 info using npm@5.6.0
3 info using node@v8.11.4
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle choerodon-front-iam@1.0.0~prestart: choerodon-front-iam@1.0.0
6 info lifecycle choerodon-front-iam@1.0.0~start: choerodon-front-iam@1.0.0
7 verbose lifecycle choerodon-front-iam@1.0.0~start: unsafe-perm in lifecycle true
8 verbose lifecycle choerodon-front-iam@1.0.0~start: PATH: /usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/Users/jalyn/front project/choerodon-front-iam/iam/node_modules/.bin:~/Library/Python/2.7/bin:/usr/local/apache-maven-3.5.2/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/mysql/bin
9 verbose lifecycle choerodon-front-iam@1.0.0~start: CWD: /Users/jalyn/front project/choerodon-front-iam/iam
10 silly lifecycle choerodon-front-iam@1.0.0~start: Args: [ '-c', 'choerodon-front-boot start --config ../config.js' ]
11 silly lifecycle choerodon-front-iam@1.0.0~start: Returned: code: 1  signal: null
12 info lifecycle choerodon-front-iam@1.0.0~start: Failed to exec start script
13 verbose stack Error: choerodon-front-iam@1.0.0 start: `choerodon-front-boot start --config ../config.js`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:285:16)
13 verbose stack     at emitTwo (events.js:126:13)
13 verbose stack     at EventEmitter.emit (events.js:214:7)
13 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at emitTwo (events.js:126:13)
13 verbose stack     at ChildProcess.emit (events.js:214:7)
13 verbose stack     at maybeClose (internal/child_process.js:925:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
14 verbose pkgid choerodon-front-iam@1.0.0
15 verbose cwd /Users/jalyn/front project/choerodon-front-iam/iam
16 verbose Darwin 16.7.0
17 verbose argv "/usr/local/bin/node" "/usr/local/bin/npm" "start"
18 verbose node v8.11.4
19 verbose npm  v5.6.0
20 error code ELIFECYCLE
21 error errno 1
22 error choerodon-front-iam@1.0.0 start: `choerodon-front-boot start --config ../config.js`
22 error Exit status 1
23 error Failed at the choerodon-front-iam@1.0.0 start script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]

```

**Comment by jalynxing** [comment]
I solved the problem by executing the command `sudo chmod -R a+rwx filepath`.
